# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCollege.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCollegeDialog(object):
    def setupUi(self, AddCollegeDialog):
        AddCollegeDialog.setObjectName("AddCollegeDialog")
        AddCollegeDialog.resize(418, 253)
        self.label = QtWidgets.QLabel(AddCollegeDialog)
        self.label.setGeometry(QtCore.QRect(110, 20, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddCollegeDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 171, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddCollegeDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 181, 41))
        self.label_3.setObjectName("label_3")
        self.collegeCode = QtWidgets.QLineEdit(AddCollegeDialog)
        self.collegeCode.setGeometry(QtCore.QRect(200, 80, 201, 41))
        self.collegeCode.setObjectName("collegeCode")
        self.collegeName = QtWidgets.QLineEdit(AddCollegeDialog)
        self.collegeName.setGeometry(QtCore.QRect(200, 130, 201, 41))
        self.collegeName.setObjectName("collegeName")
        self.pushButton = QtWidgets.QPushButton(AddCollegeDialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 190, 130, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AddCollegeDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 190, 130, 40))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AddCollegeDialog)
        QtCore.QMetaObject.connectSlotsByName(AddCollegeDialog)

    def retranslateUi(self, AddCollegeDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCollegeDialog.setWindowTitle(_translate("AddCollegeDialog", "Dialog"))
        self.label.setText(_translate("AddCollegeDialog", "Add College"))
        self.label_2.setText(_translate("AddCollegeDialog", "College Code:"))
        self.label_3.setText(_translate("AddCollegeDialog", "College Name:"))
        self.pushButton.setText(_translate("AddCollegeDialog", "Confirm"))
        self.pushButton_2.setText(_translate("AddCollegeDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddCollegeDialog = QtWidgets.QDialog()
    ui = Ui_AddCollegeDialog()
    ui.setupUi(AddCollegeDialog)
    AddCollegeDialog.show()
    sys.exit(app.exec_())
