# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProgramDialog(object):
    def setupUi(self, AddProgramDialog):
        AddProgramDialog.setObjectName("AddProgramDialog")
        AddProgramDialog.resize(421, 318)
        self.label = QtWidgets.QLabel(AddProgramDialog)
        self.label.setGeometry(QtCore.QRect(90, 10, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddProgramDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 181, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddProgramDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 181, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddProgramDialog)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 181, 41))
        self.label_4.setObjectName("label_4")
        self.programCode = QtWidgets.QLineEdit(AddProgramDialog)
        self.programCode.setGeometry(QtCore.QRect(200, 90, 201, 41))
        self.programCode.setObjectName("programCode")
        self.programName = QtWidgets.QLineEdit(AddProgramDialog)
        self.programName.setGeometry(QtCore.QRect(200, 140, 201, 41))
        self.programName.setObjectName("programName")
        self.pushButton = QtWidgets.QPushButton(AddProgramDialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 250, 130, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AddProgramDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 250, 130, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.collegeCode = QtWidgets.QComboBox(AddProgramDialog)
        self.collegeCode.setGeometry(QtCore.QRect(200, 190, 201, 41))
        self.collegeCode.setObjectName("collegeCode")

        self.retranslateUi(AddProgramDialog)
        QtCore.QMetaObject.connectSlotsByName(AddProgramDialog)

    def retranslateUi(self, AddProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        AddProgramDialog.setWindowTitle(_translate("AddProgramDialog", "Dialog"))
        self.label.setText(_translate("AddProgramDialog", "Add Program"))
        self.label_2.setText(_translate("AddProgramDialog", "Program Code:"))
        self.label_3.setText(_translate("AddProgramDialog", "Program Name:"))
        self.label_4.setText(_translate("AddProgramDialog", "College Code:"))
        self.pushButton.setText(_translate("AddProgramDialog", "Confirm"))
        self.pushButton_2.setText(_translate("AddProgramDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddProgramDialog = QtWidgets.QDialog()
    ui = Ui_AddProgramDialog()
    ui.setupUi(AddProgramDialog)
    AddProgramDialog.show()
    sys.exit(app.exec_())
