# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddStudentDialog(object):
    def setupUi(self, AddStudentDialog):
        AddStudentDialog.setObjectName("AddStudentDialog")
        AddStudentDialog.resize(424, 431)
        self.label = QtWidgets.QLabel(AddStudentDialog)
        self.label.setGeometry(QtCore.QRect(110, 10, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddStudentDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 141, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddStudentDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 141, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddStudentDialog)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 131, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AddStudentDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 131, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AddStudentDialog)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 131, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(AddStudentDialog)
        self.label_7.setGeometry(QtCore.QRect(20, 310, 171, 41))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(AddStudentDialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 370, 130, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AddStudentDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 370, 130, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.firstName = QtWidgets.QLineEdit(AddStudentDialog)
        self.firstName.setGeometry(QtCore.QRect(200, 110, 201, 41))
        self.firstName.setObjectName("firstName")
        self.IDNumber = QtWidgets.QLineEdit(AddStudentDialog)
        self.IDNumber.setGeometry(QtCore.QRect(200, 60, 201, 41))
        self.IDNumber.setObjectName("IDNumber")
        self.lastName = QtWidgets.QLineEdit(AddStudentDialog)
        self.lastName.setGeometry(QtCore.QRect(200, 160, 201, 41))
        self.lastName.setObjectName("lastName")
        self.yearLevel = QtWidgets.QComboBox(AddStudentDialog)
        self.yearLevel.setGeometry(QtCore.QRect(200, 210, 201, 41))
        self.yearLevel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.yearLevel.setObjectName("yearLevel")
        self.yearLevel.addItem("")
        self.yearLevel.addItem("")
        self.yearLevel.addItem("")
        self.yearLevel.addItem("")
        self.gender = QtWidgets.QComboBox(AddStudentDialog)
        self.gender.setGeometry(QtCore.QRect(200, 260, 201, 41))
        self.gender.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.programCode = QtWidgets.QComboBox(AddStudentDialog)
        self.programCode.setGeometry(QtCore.QRect(200, 310, 201, 41))
        self.programCode.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.programCode.setObjectName("programCode")

        self.retranslateUi(AddStudentDialog)
        QtCore.QMetaObject.connectSlotsByName(AddStudentDialog)

    def retranslateUi(self, AddStudentDialog):
        _translate = QtCore.QCoreApplication.translate
        AddStudentDialog.setWindowTitle(_translate("AddStudentDialog", "Dialog"))
        self.label.setText(_translate("AddStudentDialog", "Add Student"))
        self.label_2.setText(_translate("AddStudentDialog", "ID Number:"))
        self.label_3.setText(_translate("AddStudentDialog", "First Name:"))
        self.label_4.setText(_translate("AddStudentDialog", "Last Name:"))
        self.label_5.setText(_translate("AddStudentDialog", "Year Level:"))
        self.label_6.setText(_translate("AddStudentDialog", "Gender:"))
        self.label_7.setText(_translate("AddStudentDialog", "Program Code:"))
        self.pushButton.setText(_translate("AddStudentDialog", "Confirm"))
        self.pushButton_2.setText(_translate("AddStudentDialog", "Cancel"))
        self.yearLevel.setItemText(0, _translate("AddStudentDialog", "1"))
        self.yearLevel.setItemText(1, _translate("AddStudentDialog", "2"))
        self.yearLevel.setItemText(2, _translate("AddStudentDialog", "3"))
        self.yearLevel.setItemText(3, _translate("AddStudentDialog", "4"))
        self.gender.setItemText(0, _translate("AddStudentDialog", "M"))
        self.gender.setItemText(1, _translate("AddStudentDialog", "F"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddStudentDialog = QtWidgets.QDialog()
    ui = Ui_AddStudentDialog()
    ui.setupUi(AddStudentDialog)
    AddStudentDialog.show()
    sys.exit(app.exec_())
